### ISSUE TITLE
Write unit tests for existing basic classes

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/synthia#4]
Some sources of inspiration...

For most pickers:

- [x] For each class, make sure that a duplicate obtained *without* copying state (i.e. calling `duplicate(false)`) restarts its sequence from the beginning of the original
- [x] For each class, make sure that a duplicate obtained *with* copying state (i.e. calling `duplicate(true)`) continues producing the same values as the original from that point (this case is expected to **fail** in the current implementation of a few classes, because of #5)

For Constant pickers:

- [x] Observe that they produce the expected constant

For `Playback`:

- [x] Observe that it produces the expected sequence
- [x] If `loop` is set to false, observe that it throws a `NoMoreElementException` after producing the last element of the list (see #3)

For pickers based on random generators:

- [x] For each class, make sure that two pickers with the same seed produce the same events (loop for the first few events to make sure)

For pickers producing numbers within an interval (and implementations of `IndexPicker`):

- [x] For each class, observe that the values are indeed in the interval
- [x] For the `PrismPicker` and the `HyperspherePicker`, make sure that the values in each dimension are within their specified bounds

For pickers producing a string of given length:

- [x] For each class, observe that the string length is indeed in the interval

For pickers 

For `AffineTransform`:

- [x] Observe that it produces the expected output value from an expected input (hint: use a `Constant` or a `Playback` so that you control what it receives)

For `Once`:

- [x] Make sure it produces only one event, and output an `NoMoreElementException` after that (see #3)

For `Tick`:

- [x] Observe that each successive output increments by the expected value (hint: use a `Constant` or a `Playback` for its parameters, so that you control what it receives)

For `Record`:

- [x] Observe that the values it records are indeed those it receives
- [x] Make sure that `reset` wipes these values and makes the recording start anew
- [x] Check that `getCount` returns the expected value

For `SetPicker` and `ArrayPicker`:

- [x] Make sure that the set contains exactly one value produced by each picker every time (hint: use pickers with disjoint images to distinguish them)

For `StringPattern`:

- [x] Check that the produced string has the expected pattern (hint: use a `Constant` or a `Playback` for its parameters, so that you control what it receives)

For `Freeze`:

- [x] Make sure it always returns the first value produced by the underlying picker
- [x] Make sure that resets cancels this (i.e. it outputs a new value. Hint: use a `Playback` to control what the picker receives)

For `ElementPicker`:

-  [x] Check that the choice respects the set probabilities (check this partially by setting the probability to 1 for an element, and 0 for the others)
